# Trading Bot YAML Configuration
# This file allows you to override any configuration parameter
# All settings are optional - if not specified, defaults will be used

# Trading Configuration
trading:
  # Position sizing
  base_position_size: 50.0        # Base amount per trade in USD
  max_position_size: 80.0         # Maximum per trade
  min_position_size: 20.0         # Minimum per trade
  
  # Trading limits
  max_daily_trades: 50            # Maximum trades per day
  max_positions: 4                # Maximum concurrent positions
  trade_cooldown: 90              # Seconds between trades on same symbol
  max_daily_loss: 15.0            # Maximum daily loss in USD
  
  # Strategy settings
  min_confidence_threshold: 0.25  # Minimum confidence to execute trade
  
  # Exchange settings
  default_exchange: "gemini"      # Options: gemini, binance, kraken
  
  # Data settings
  save_trades_to_csv: true        # Save trades to CSV file
  
  # Partial selling
  partial_sell_enabled: true      # Enable partial selling
  first_sell_percentage: 0.5     # First sell percentage
  second_sell_percentage: 1.0    # Second sell percentage

# Risk Management Configuration
risk_management:
  # Stop-loss settings
  stop_loss_enabled: true         # Enable stop-loss orders
  stop_loss_percentage: 0.05      # 5% stop-loss
  
  # Take-profit settings
  take_profit_enabled: true       # Enable take-profit orders
  take_profit_percentage: 0.10    # 10% take-profit
  
  # Position risk
  max_position_risk: 0.02         # Max 2% portfolio risk per position
  max_portfolio_risk: 0.06        # Max 6% total portfolio risk
  
  # Daily limits
  max_daily_loss_percentage: 0.03 # 3% max daily loss
  max_daily_loss_usd: 100.0       # $100 max daily loss
  
  # Drawdown protection
  max_drawdown_percentage: 0.10   # 10% max drawdown
  
  # Risk monitoring
  monitor_drawdown: true          # Monitor drawdown
  pause_on_drawdown: true         # Pause trading on max drawdown

# Constants Configuration
constants:
  # Timing
  default_cycle_delay: 120        # Default trading cycle delay (seconds)
  min_sleep_time: 20              # Minimum sleep between cycles
  sleep_countdown_interval: 10    # Countdown update interval
  
  # Retry settings
  default_max_retries: 3          # Maximum retry attempts
  max_retry_delay: 300            # Maximum retry delay (seconds)
  
  # Performance
  performance_window_size: 20     # Trades to track for performance
  min_trades_for_win_rate: 5      # Min trades to calculate win rate
  
  # Safety margins
  cash_reserve_percentage: 0.1    # Keep 10% cash reserve
  fee_profit_buffer: 0.002        # Additional profit buffer

# Logging Configuration
logging:
  level: "INFO"                   # Log level: DEBUG, INFO, WARNING, ERROR
  log_trades: true                # Enable trade logging
  log_performance: true           # Enable performance logging
  max_log_size_mb: 10            # Maximum log file size
  backup_count: 5                 # Number of backup log files

# Development Settings
development:
  debug_mode: false               # Enable debug mode
  verbose_logging: false          # Enable verbose logging
  use_synthetic_data: false       # Use synthetic data for testing